name: ScottDixonPhotography
favicon: null
layout_spectrum: 0.28829
typography_spectrum: 0.90067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#313131'
    - '#c4c4c4'
    - '#6a6a6a'
  brandStrength: 0.7218227179255337
  lightness: 0.975655855378136
  saturation: 0.19838367868214846
  rhythmicContrast: 0.26094389078207314
purpose: []
